application: luna-morada
runtime: python3
version: 1
api: version
threadsafe: true

handlers:
- url: .*
  script: luna.wsgi.application

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: django
  version: "1.7"

builtins:
- django_wsgi: on
